apiVersion: v1   #Which version of the Kubernetes API you're using to create this object
kind: ConfigMap  #What kind of object you want to create
metadata:  
  name: webappdb-configmap 
data:
  database_host: webapp-db-service 